Better exception type for missing ObjectMapper
`NoClassDefFoundError` is misleading as the class is there only the bean is missing.

(cherry picked from commit ae7931cf667331770af583d8eb89959b4d4bf96a)